kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: istio-ingress
subjects:
  - kind: ServiceAccount
    name: istio-ingress
    namespace: default
roleRef:
  kind: ClusterRole
  name: istio-ingress
  apiGroup: rbac.authorization.k8s.io
